### ISSUE TITLE
Need te-weakness old version 

### ISSUE THREAD

**Issue by Zetthh** [TeamVK/Support#3]
Need te-weakness old version to tokenenchant 13.8 please

https://www.spigotmc.org/resources/te-weaknessenchant.20216/update?update=224816

thanks

**Comment by Zetthh** [comment]
because have this error with april version te-weakness, if u can send me old te-weakness version I would greatly appreciate it :D i use 13.8 tokenenchant and work perfect. i m Zetth_ (spigot and discord i speak today)

[08:47:50] [Server thread/INFO]: [TE] Class WeaknessPotion could not be registered
[08:47:50] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[08:47:50] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:47:50] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:47:50] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:47:50] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.potions.PotionHandlerImpl.loadHandlers(PotionHandlerImpl.java:66)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.j.a(j.java:266)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.a.a.k.a.reload(a.java:33)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.j.reloadConfig(j.java:182)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.h.c(h.java:207)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.h.onCommand(h.java:109)
[08:47:50] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:47:50] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:47:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:47:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:47:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:47:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:47:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:47:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:47:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[08:47:50] [Server thread/WARN]: Caused by: java.lang.Exception: Rquires TokenEnchant ver.13.19
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.api.PotionHandler.<init>(PotionHandler.java:69)
[08:47:50] [Server thread/WARN]: 	at com.vk2gpz.tokenenchant.potions.WeaknessPotion.<init>(WeaknessPotion.java:23)
[08:47:50] [Server thread/WARN]: 	... 19 more

**Comment by vk2gpz** [comment]
I posted jar file on discord, please download it.
